apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hlf-ordnode.fullname" . }}-admincert
  labels:
{{ include "labels.standard" . | indent 4 }}
type: Opaque
data:
  admin-cert.pem: {{ .Values.adminCert | b64enc | quote }}
