apiVersion: v1
kind: Service
metadata:
  name: {{ include "hlf-ordnode.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7050
      protocol: TCP
      name: grpc

{{- if and (eq .Values.service.type "NodePort") (gt .Values.service.nodePort 29999.0) }}
      nodePort: {{.Values.service.nodePort}}
{{- end }}
{{- if .Values.channelParticipationEnabled }}
    - port: 7053
      targetPort: 7053
      protocol: TCP
      name: admin
{{- end }}
    - port: {{ .Values.service.portOperations }}
      targetPort: 9444
      protocol: TCP
      name: operations
{{- if and (eq .Values.service.type "NodePort") (gt .Values.service.nodePortOperations 29999.0) }}
      nodePort: {{.Values.service.nodePortOperations}}
{{- end }}
  selector:
    app: {{ include "hlf-ordnode.name" . }}
    release: {{ .Release.Name }}
