{{- if .Values.operationHosts -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "hlf-peer.fullname" . }}-ops-virtualservice
spec:
  hosts:
    {{- range .Values.operationHosts }}
    - {{ . }}
    {{- end }}
  gateways:
    - {{ include "hlf-peer.fullname" . }}-ops-gateway
  tls:
    - match:
        - port: 443
          sniHosts:
          {{- range .Values.operationHosts }}
              - {{ . }}
          {{- end }}
      route:
        - destination:
            host: {{ include "hlf-peer.fullname" . }}
            port:
              number: 9443
{{- end -}}
