apiVersion: v1
kind: Service
metadata:
  name: {{ include "hlf-peer.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portRequest }}
      targetPort: 7051
      protocol: TCP
{{- if (and (eq .Values.service.type "NodePort") (not ( empty .Values.service.nodePortRequest)))  }}
      nodePort: {{.Values.service.nodePortRequest}}
{{- end }}
      name: request
    - port: {{ .Values.service.portEvent }}
      targetPort: 7053
{{- if (and (eq .Values.service.type "NodePort") (not ( empty .Values.service.nodePortEvent)))  }}
      nodePort: {{.Values.service.nodePortEvent}}
{{- end }}
      protocol: TCP
      name: event
    - port: {{ .Values.service.portOperations }}
      targetPort: 9443
{{- if (and (eq .Values.service.type "NodePort") (not ( empty .Values.service.nodePortOperations)))  }}
      nodePort: {{.Values.service.nodePortOperations}}
{{- end }}
      protocol: TCP
      name: operations
  selector:
    app: {{ include "hlf-peer.name" . }}
    release: {{ .Release.Name }}
