{{- range $index, $vv := .Values.nodes }}
apiVersion: hlf.kungfusoftware.es/v1alpha1
kind: FabricOrdererNode
metadata:
  name: {{ include "hlf-ord.fullname" $ }}--ord-{{$index}}
  labels:
{{- include "labels.standard" $ | nindent 6 }}
spec:
  image: {{ $.Values.image.repository}}
  tag: {{ $.Values.image.tag}}
  pullPolicy: {{ $.Values.image.pullPolicy}}
  mspID: {{ $.Values.mspID}}
  genesis: {{ $.Values.genesis}}
  storage:
    accessMode: {{ $.Values.storage.accessMode}}
    storageClass: {{ $.Values.storage.storageClass}}
    size: {{ $.Values.storage.size}}
  hosts: {{$vv.hosts}}
  service:
    nodePortRequest: {{ $vv.service.nodePortRequest }}
    type: {{ $vv.service.type }}

  signCert: |
{{- $vv.signCert| nindent 4}}
  signKey: |
{{- $vv.signKey | nindent 4}}
  signRootCert: |
{{- $vv.signRootCert | nindent 4}}

  tlsCert: |
{{- $vv.tlsCert | nindent 4}}
  tlsKey: |
{{- $vv.tlsKey | nindent 4}}
  tlsRootCert: |
{{- $vv.tlsRootCert | nindent 4}}
---
{{- end }}