---
Organizations:
  - Name: Org1MSP

    ID: Org1MSP

    MSPDir: crypto-config/Org1MSP/msp
    MSPType: bccsp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Org1MSP.admin', 'Org1MSP.peer', 'Org1MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('Org1MSP.admin', 'Org1MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('Org1MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Org1MSP.peer')"

    AnchorPeers:
      - Host: 172.24.0.2
        Port: 32149
