apiVersion: hlf.kungfusoftware.es/v1alpha1
kind: FabricCA
metadata:
  name: org1-ca
spec:
  ca:
    bccsp:
      default: SW
      sw:
        hash: SHA2
        security: "256"
    cfg:
      affiliations:
        allowRemove: true
      identities:
        allowRemove: true
    crl:
      expiry: 24h
    csr:
      ca:
        expiry: 131400h
        pathLength: 0
      cn: ca
      hosts:
        - 172.24.0.2
        - org1-ca
        - org1-ca.org1
      names:
        - C: US
          L: ""
          O: Hyperledger
          OU: North Carolina
          ST: ""
    intermediate:
      parentServer:
        caName: ""
        url: ""
    name: ca
    registry:
      identities:
        - affiliation: ""
          attrs:
            hf.AffiliationMgr: true
            hf.GenCRL: true
            hf.IntermediateCA: true
            hf.Registrar.Attributes: '*'
            hf.Registrar.DelegateRoles: '*'
            hf.Registrar.Roles: '*'
            hf.Revoker: true
          name: enroll
          pass: enrollpw
          type: client
        - affiliation: ""
          attrs:
            hf.AffiliationMgr: true
            hf.GenCRL: true
            hf.IntermediateCA: true
            hf.Registrar.Attributes: '*'
            hf.Registrar.DelegateRoles: '*'
            hf.Registrar.Roles: '*'
            hf.Revoker: true
          name: peer
          pass: peerpw
          type: peer
      max_enrollments: -1
    subject:
      C: US
      L: Delware
      O: Arise Technologies
      OU: Tech
      ST: Delaware
      cn: ca
  clrSizeLimit: 512000
  cors:
    enabled: false
    origins: []
  db:
    datasource: fabric-ca-server.db
    type: sqlite3
  debug: false
  hosts:
    - 172.24.0.2
    - org1-ca
    - org1-ca.org1
  image: hyperledger/fabric-ca
  metrics:
    provider: prometheus
    statsd:
      address: 127.0.0.1:8125
      network: udp
      prefix: server
      writeInterval: 10s
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: 10m
      memory: 256Mi
  rootCA:
    subject:
      C: California
      L: ""
      O: Hyperledger
      OU: Fabric
      ST: ""
      cn: ca
  service:
    type: NodePort
  storage:
    accessMode: ReadWriteOnce
    size: 2Gi
    storageClass: ""
  tlsCA:
    bccsp:
      default: SW
      sw:
        hash: SHA2
        security: "256"
    cfg:
      affiliations:
        allowRemove: true
      identities:
        allowRemove: true
    crl:
      expiry: 24h
    csr:
      ca:
        expiry: 131400h
        pathLength: 0
      cn: tlsca
      hosts:
        - 172.24.0.2
        - org1-ca
        - org1-ca.org1
      names:
        - C: US
          L: ""
          O: Hyperledger
          OU: North Carolina
          ST: ""
    intermediate:
      parentServer:
        caName: ""
        url: ""
    name: tlsca
    registry:
      identities:
        - affiliation: ""
          attrs:
            hf.AffiliationMgr: true
            hf.GenCRL: true
            hf.IntermediateCA: true
            hf.Registrar.Attributes: '*'
            hf.Registrar.DelegateRoles: '*'
            hf.Registrar.Roles: '*'
            hf.Revoker: true
          name: enroll
          pass: enrollpw
          type: client
      max_enrollments: -1
    subject:
      C: US
      L: Delware
      O: Arise Technologies
      OU: Tech
      ST: Delaware
      cn: tlsca
  version: 1.4.9
